export const COPY = {
  heroEyebrow: "Now Showing",
  heroTagline: "Lead Frontend Engineer — Garnishes UIs With Wit Since 2015",
  profileLabel: "About the Engineer",
  profileHeading: "The Profile",
  skillsLabel: "The Marquee of Skills",
  experienceLabel: "Featured Engagements",
  experienceHeading: "The Marquee",
  educationLabel: "Diplomas & Distinctions",
  footerLine: "Hand-set in San Francisco. Not tested on focus groups.",
};

export const PROFILE = {
  name: "Paul-Valentin Mini",
  location: "San Francisco, CA",
  phone: "(415) 694-3616",
  email: "paul@emini.com",
  linkedin: "https://www.linkedin.com/in/pvmini",
  github: "https://github.com/Laptopmini",
  summary:
    "Lead Frontend Engineer with over 10 years of experience designing and scaling web and mobile applications for global platforms like Samsung SmartThings. Expert in React, Next.js, and modern JavaScript ecosystems, with a proven track record of overhauling developer consoles and building robust internal component libraries. Recently expanded focus into Applied AI, leveraging Generative AI tooling and prompt engineering to accelerate developer workflows and bootstrap product integrations.",
};

export const SKILL_GROUPS: { label: string; items: string[] }[] = [
  {
    label: "Frontend & Web",
    items: ["JavaScript", "TypeScript", "React", "Next.js", "HTML/CSS"],
  },
  {
    label: "AI & Machine Learning",
    items: [
      "Applied Prompt Engineering",
      "LLM Integration (Claude, Gemini, Copilot)",
      "Computer Vision (OpenCV, Tesseract)",
    ],
  },
  {
    label: "Infrastructure & DevOps",
    items: [
      "Docker",
      "Kubernetes",
      "Terraform",
      "GitHub Actions",
      "Jenkins",
      "Spinnaker",
      "JFrog Artifactory (NPM)",
    ],
  },
  {
    label: "Backend & Mobile",
    items: ["Python", "Swift", "PostgreSQL", "REST API Design", "iOS/Android Development"],
  },
];

export const EXPERIENCE: {
  company: string;
  location: string;
  role: string;
  period: string;
  bullets: { heading: string; body: string }[];
  stack: string[];
}[] = [
  {
    company: "SmartThings, Inc.",
    location: "San Francisco, CA",
    role: "Senior Software Developer",
    period: "January 2020 – Present",
    bullets: [
      {
        heading: "Frontend Architecture & Global Leadership",
        body: "Lead developer for the SmartThings Developer Console, unifying UX across multiple web products while partnering with global teams (Poland, Indonesia, Korea) to integrate cross-functional features.",
      },
      {
        heading: "AI Integration & Tooling",
        body: "Actively contributed to the company's AI pilot program as a designated power user. Engineered a template repository providing AI-driven prompts and skills to bootstrap product integrations.",
      },
      {
        heading: "End-to-End Product Leadership",
        body: "Initiated and led the complete refactoring of the platform's onboarding experience, taking proactive ownership to drive the project from proof-of-concept to a successful production release.",
      },
      {
        heading: "Developer Experience (DX) Infrastructure",
        body: "Streamlined platform development by building a React component library that enforced Samsung's One Design guidelines to unify cross-brand UX, managing zero-break global NPM releases, and maintaining a JavaScript SDK autogenerated from OpenAPI specifications.",
      },
    ],
    stack: [
      "JavaScript",
      "TypeScript",
      "React",
      "Next.js",
      "Docker",
      "Spinnaker",
      "Kubernetes",
      "Terraform",
      "GitHub Actions",
      "Jenkins",
      "Copilot",
      "Claude",
      "Gemini",
      "Python",
    ],
  },
  {
    company: "Samsung Research America",
    location: "San Francisco, CA",
    role: "Software Developer",
    period: "March 2018 – January 2020",
    bullets: [
      {
        heading: "Frontend Transition",
        body: "Transitioned to web frontend development for ARTIK Cloud, instrumental in launching the Developer Workspace (a portal for managing SmartThings integrations).",
      },
      {
        heading: "SDK Development",
        body: "Developed a modern JavaScript SDK and specialized Starter Kits to improve the 3rd-party developer experience.",
      },
      {
        heading: "Cross-Platform Maintenance",
        body: "Maintained ARTIK Cloud's iOS developer tooling alongside web responsibilities.",
      },
    ],
    stack: [
      "JavaScript",
      "TypeScript",
      "React",
      "Next.js",
      "Docker",
      "Spinnaker",
      "Kubernetes",
      "Swift",
      "App Store Connect",
      "TestFlight",
    ],
  },
  {
    company: "Samsung Strategy & Innovation Center",
    location: "San Francisco, CA",
    role: "iOS Developer",
    period: "June 2016 – March 2018",
    bullets: [
      {
        heading: "Executive Collaboration",
        body: "Hired directly under executive leadership (Luc Julia, co-creator of Siri) to served as the lead iOS developer for ARTIK Cloud.",
      },
      {
        heading: "App Engineering",
        body: "Conceptualized and engineered the ARTIK Cloud iOS application from the ground up.",
      },
      {
        heading: "Universal SDK",
        body: "Developed and maintained a Universal Framework (SDK) enabling 3rd-party developers to build natively across iOS, tvOS, watchOS, and macOS.",
      },
      {
        heading: "OS Optimization",
        body: "Navigated strict Apple OS limitations (background task restrictions, location tracking) to ensure seamless application performance and reliable data syncing.",
      },
    ],
    stack: ["Swift", "Objective-C", "App Store Connect", "TestFlight"],
  },
  {
    company: "Prism, Inc.",
    location: "San Francisco, CA",
    role: "iOS & Backend Developer",
    period: "October 2015 – May 2016",
    bullets: [
      {
        heading: "Full-Stack Engineering",
        body: "Engineered an iOS application and its supporting backend architecture designed for automated, smart image classification.",
      },
      {
        heading: "Computer Vision",
        body: "Pioneered a computer vision–driven photo classification system predating native iOS Visual Search, utilizing OpenCV, Tesseract, and Python to identify apps from screenshots and execute Deep Link Lookups.",
      },
      {
        heading: "API Architecture",
        body: "Designed a highly performant and scalable REST API backed by a PostgreSQL database with Redis caching.",
      },
    ],
    stack: ["Python", "Django", "PostgreSQL", "Redis", "SQLite", "tesseract-ocr", "OpenCV"],
  },
  {
    company: "Imprivata",
    location: "Santa Cruz, CA",
    role: "Android Developer (Capstone Partnership)",
    period: "January 2015 – August 2015",
    bullets: [
      {
        heading: "HIPAA-Compliant Mobile App",
        body: "Developed an end-to-end encrypted Android application to facilitate secure, confidential document sharing between patients and medical professionals in strict accordance with HIPAA regulations.",
      },
      {
        heading: "Data Synchronization",
        body: "Architected the data synchronization flow using an internal SQLite database communicating with a Python/MySQL backend.",
      },
    ],
    stack: ["Java", "Android Studio", "MySQL", "SQLite", "REST", "Python"],
  },
];

export const EDUCATION: { line: string }[] = [
  { line: "B.A. Computer Science • University of California, Santa Cruz (UCSC)" },
  {
    line: "Practical Prompt Engineering – Instructor: Sabrina Goldfarb (GitHub) | *Completed Dec 2025*",
  },
  { line: "AI Agents Fundamentals, v2 – Instructor: Scott Moss (Netflix) | *In Progress*" },
];
